frontpage:
    path: /
    defaults:  { _controller: LinkORB\Skeleton\Controller\ThingController::frontpageAction }

# Authentication
login:
    path: /login
    defaults:  { _controller: LinkORB\Skeleton\Controller\AuthenticationController::loginAction }
    
login_check:
    path: /authentication/login_check

# CRUD example
things_index:
    path: /things
    defaults:  { _controller: LinkORB\Skeleton\Controller\ThingController::indexAction }

things_add:
    path: /things/add
    defaults:  { _controller: LinkORB\Skeleton\Controller\ThingController::addAction }
things_view:
    path: /things/{thingId}
    defaults:  { _controller: LinkORB\Skeleton\Controller\ThingController::viewAction }
things_edit:
    path: /things/{thingId}/edit
    defaults:  { _controller: LinkORB\Skeleton\Controller\ThingController::editAction }
things_delete:
    path: /things/{thingId}/delete
    defaults:  { _controller: LinkORB\Skeleton\Controller\ThingController::deleteAction }

# API routes

api_root:
    path: /api/v1
    defaults:  { _controller: LinkORB\Skeleton\Controller\ApiController::rootAction }
